[profile.default]
  auto_detect_solc = false
  bytecode_hash = "none"
  evm_version = "shanghai"
  fs_permissions = [
    { access = "read", path = "./out-optimized" },
    { access = "read", path = "package.json" },
    { access = "read-write", path = "./benchmark/results"},
    { access = "read-write", path = "./script"}
  ]
  gas_limit = 9223372036854775807
  gas_reports = ["SablierFlow"]
  optimizer = true
  optimizer_runs = 1000
  out = "out"
  script = "script"
  sender = "0x1804c8AB1F12E6bbf3894d4083f33e07309d1f38"
  solc = "0.8.26"
  src = "src"
  test = "tests"

[profile.default.fuzz]
  max_test_rejects = 1_000_000 # Number of times `vm.assume` can fail
  runs = 10000

[profile.default.invariant]
  call_override = false # Override unsafe external calls to perform reentrancy checks
  dictionary_weight = 50
  depth = 100           # Number of calls executed in one run
  fail_on_revert = true
  runs = 1000
  shrink_run_limit = 0 # Disable shrinking of a failed sequence

# Run only the code inside benchmark directory
[profile.benchmark]
  test = "benchmark"

# Speed up compilation and tests during development
[profile.lite]
  optimizer = false

[profile.lite.invariant]
  depth = 50
  runs = 50

[profile.lite.fuzz]
  runs = 20

# Compile only the production code and the test mocks with via IR and 10,000 optimizer runs
[profile.optimized]
  optimizer = true
  optimizer_runs = 10_000
  out = "out-optimized"
  test = "tests/mocks"
  via_ir = true

# Test the optimized contracts without re-compiling them
[profile.test-optimized]
  src = "tests"

[doc]
  ignore = ["**/*.t.sol"]
  out = "docs"
  repository = "https://github.com/sablier-labs/flow"

[etherscan]
  etherscan = { key = "${ETHERSCAN_API_KEY}" }

[fmt]
  bracket_spacing = true
  int_types = "long"
  line_length = 120
  multiline_func_header = "all"
  number_underscore = "thousands"
  quote_style = "double"
  tab_width = 4
  wrap_comments = true

[rpc_endpoints]
  # mainnets
  arbitrum = "https://direct.routeme.sh/rpc/42161/${ROUTEMESH_API_KEY}"
  avalanche = "https://direct.routeme.sh/rpc/43114/${ROUTEMESH_API_KEY}"
  base = "https://direct.routeme.sh/rpc/8453/${ROUTEMESH_API_KEY}"
  berachain = "https://direct.routeme.sh/rpc/80094/${ROUTEMESH_API_KEY}"
  blast = "https://direct.routeme.sh/rpc/81457/${ROUTEMESH_API_KEY}"
  bsc = "https://direct.routeme.sh/rpc/56/${ROUTEMESH_API_KEY}"
  ethereum = "https://direct.routeme.sh/rpc/1/${ROUTEMESH_API_KEY}"
  chiliz = "https://direct.routeme.sh/rpc/88888/${ROUTEMESH_API_KEY}"
  core_dao = "https://direct.routeme.sh/rpc/1116/${ROUTEMESH_API_KEY}"
  form = "https://direct.routeme.sh/rpc/478/${ROUTEMESH_API_KEY}"
  gnosis = "https://direct.routeme.sh/rpc/100/${ROUTEMESH_API_KEY}"
  lightlink = "https://direct.routeme.sh/rpc/1890/${ROUTEMESH_API_KEY}"
  linea = "https://direct.routeme.sh/rpc/59144/${ROUTEMESH_API_KEY}"
  mode = "https://direct.routeme.sh/rpc/34443/${ROUTEMESH_API_KEY}"
  morph = "https://direct.routeme.sh/rpc/2818/${ROUTEMESH_API_KEY}"
  optimism = "https://direct.routeme.sh/rpc/10/${ROUTEMESH_API_KEY}"
  polygon = "https://direct.routeme.sh/rpc/137/${ROUTEMESH_API_KEY}"
  scroll = "https://direct.routeme.sh/rpc/534352/${ROUTEMESH_API_KEY}"
  sei = "https://direct.routeme.sh/rpc/1329/${ROUTEMESH_API_KEY}"
  superseed = "https://direct.routeme.sh/rpc/5330/${ROUTEMESH_API_KEY}"
  xdc = "https://direct.routeme.sh/rpc/50/${ROUTEMESH_API_KEY}"
  # testnets
  arbitrum_sepolia = "https://direct.routeme.sh/rpc/421614/${ROUTEMESH_API_KEY}"
  base_sepolia = "https://direct.routeme.sh/rpc/84532/${ROUTEMESH_API_KEY}"
  blast_sepolia = "https://direct.routeme.sh/rpc/168587773/${ROUTEMESH_API_KEY}"
  linea_sepolia = "https://direct.routeme.sh/rpc/59141/${ROUTEMESH_API_KEY}"
  localhost = "http://localhost:8545"
  mode_sepolia = "https://direct.routeme.sh/rpc/919/${ROUTEMESH_API_KEY}"
  monad_testnet = "https://direct.routeme.sh/rpc/10143/${ROUTEMESH_API_KEY}"
  optimism_sepolia = "https://direct.routeme.sh/rpc/11155420/${ROUTEMESH_API_KEY}"
  sei_testnet = "https://direct.routeme.sh/rpc/713715/${ROUTEMESH_API_KEY}"
  sepolia = "https://direct.routeme.sh/rpc/11155111/${ROUTEMESH_API_KEY}"
  superseed_sepolia = "https://sepolia.superseed.xyz"
