name: "Verify the specs of concrete tests using bulloak"

on: "workflow_call"

jobs:
  bulloak-check:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Check out the repo"
        uses: "actions/checkout@v4"

      - name: "Install Rust"
        uses: "actions-rs/toolchain@v1"
        with:
          toolchain: "stable"

      - name: "Install bulloak"
        run: "cargo install bulloak"

      - name: "Verify the concrete tests"
        run: "bulloak check test/integration/concrete/**/**.tree --skip-modifiers"

      - name: "Bulloak summary"
        run: |
          echo "## Bulloak result" >> $GITHUB_STEP_SUMMARY
          echo "✅ Passed" >> $GITHUB_STEP_SUMMARY
