name: "CI"

concurrency:
  cancel-in-progress: true
  group: ${{github.workflow}}-${{github.ref}}

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - "main"
      - "staging"

jobs:
  lint:
    uses: "sablier-labs/reusable-workflows/.github/workflows/forge-lint.yml@feat/paths-filter"

  bulloak:
    needs: ["lint"]
    uses: "sablier-labs/reusable-workflows/.github/workflows/bulloak-check.yml@feat/paths-filter"
    with:
      skip-modifiers: true
      tree-path: "tests/integration"

  build:
    uses: "sablier-labs/reusable-workflows/.github/workflows/forge-build.yml@feat/paths-filter"

  test-integration:
    needs: ["lint", "build"]
    uses: "sablier-labs/reusable-workflows/.github/workflows/forge-test.yml@feat/paths-filter"
    with:
      foundry-fuzz-runs: 10000
      foundry-profile: "test-optimized"
      match-path: "tests/integration/**/*.sol"
      name: "Integration tests"

  test-invariant:
    needs: ["lint", "build"]
    uses: "sablier-labs/reusable-workflows/.github/workflows/forge-test.yml@feat/paths-filter"
    with:
      foundry-invariant-depth: 100
      foundry-invariant-runs: 1000
      foundry-profile: "test-optimized"
      match-path: "tests/invariant/**/*.sol"
      name: "Invariant tests"

  test-fork:
    needs: ["lint", "build"]
    secrets:
      MAINNET_RPC_URL: ${{ secrets.MAINNET_RPC_URL }}
    uses: "sablier-labs/reusable-workflows/.github/workflows/forge-test.yml@feat/paths-filter"
    with:
      foundry-fuzz-runs: 20
      foundry-profile: "test-optimized"
      match-path: "tests/fork/**/*.sol"
      name: "Fork tests"

  coverage:
    needs: ["lint", "build"]
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    uses: "sablier-labs/reusable-workflows/.github/workflows/forge-coverage.yml@feat/paths-filter"
    with:
      match-path: "tests/{integration}/**/*.sol"
